### ISSUE TITLE
Binding to KO template

### ISSUE THREAD

**Issue by ArjunMenonUK** [aknuds1/knockout-isotope#9]
Hi Arve,

I was looking for a solution to integrate KO & isotope and came across your article in GitHub. First of all thanks for the wonderful article. But since am new to KO & isotope I have some doubts.
1. I have implemented KO in my project now i want to implement Isotope filtering. I am binding the data using template (KO) like this. 

`<ul class="cd-filters tabUlStyle noPadding" data-bind="template: { name: 'Report-Filter', foreach: QlikViewData().Filters }"></ul>`

`<script type="text/html" id="Report-Filter">
    <li class="placeholder">
        <input type="button" class="FltrBtn FltrBtn_active" data-bind="click: function () { filter(FilterLinkID, ProductID, this) }, value: FilterName, attr: { id: 'Filter_' + ProductID + '_' + FilterID }, css: { 'FltrBtn_active': $index() == 0 } " />
    </li>
</script>`

As you can see am using an AJAX call to hide the data while filtering and from what i have understood of Isotope , the filtering is done internally by using data-filter property. So as per your example we can use the filterClass to set the hiding things, but say i have 2 filter buttons A & B and 5 divs , first belonging to filter A and rest two to filterB . So when i click button A , how can we hide the divs belonging to filter B ?

If possible can you help me as its kind of urgent and i am not given enuf time to go through the things and implement :(

Thanks in advance

**Comment by aknuds1** [comment]
Hi, don't have the time to help you now sorry. I would ask on StackOverflow instead, this sounds like a JavaScript problem.
